### ISSUE TITLE
Stroke Color and Width merges incorrectly

### ISSUE THREAD

**Issue by austin-thrive** [dcastil/tailwind-merge#149]
This is likely very similar to #67 except for the inclusion of custom values.

Example: `stroke-[3] stroke-current` I would expect to not conflict, but will output `stroke-current` only.

**Comment by dcastil** [comment]
Hey @austin-thrive! 👋 

Just tested this. The reason is that stroke width is a length and tailwind-merge doesn't identify it without any length unit. So correct would be to use `stroke-[3px] stroke-current` which tailwind-merge would handle correctly.

I just tested this and found out that `stroke-[3]` also works in Tailwind and CSS which surprised me. Probably SVG handles purely numerical values as `px`? 🤔

Do you have a use case for using `stroke-[3]` instead of `stroke-[3px]`?

**Comment by dcastil** [comment]
Okay, I think if this is officially supported by Tailwind CSS, tailwind-merge should support that too. I'll work out a fix soon!
