### ISSUE TITLE
it doesn't work with storybook

### ISSUE THREAD

**Issue by krzysztofpniak** [dcastil/tailwind-merge#192]
I got a lot of errors like the following in version 1.9.0:

ERROR in ./node_modules/tailwind-merge/dist/lib/config-utils.mjs 9:7-23
Can't import the named export 'createClassUtils' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/tailwind-merge/dist/lib/default-config.mjs 65:15-20
Can't import the named export 'isAny' from non EcmaScript module (only default export is available)

**Comment by dcastil** [comment]
Hey @krzysztofpniak! 👋

That's a weird bug. 🤔 Those modules are all EcmaScript modules and none of them use default exports. E.g. here is the code from those files in `tailwind-merge@1.9.0`

```js
// tailwind-merge/dist/lib/config-utils.mjs

import { createClassUtils } from './class-utils.mjs';
import { createLruCache } from './lru-cache.mjs';
import { createSplitModifiers } from './modifier-utils.mjs';

// internal code

export { createConfigUtils };
//# sourceMappingURL=config-utils.mjs.map
```

```js
// tailwind-merge/dist/lib/class-utils.mjs

// internal code

export { createClassMap, createClassUtils };
//# sourceMappingURL=class-utils.mjs.map
```


Do you have a minimal reproduction example for your bug? Might be that something in your toolchain is converting the ES modules to CJS.

**Comment by krzysztofpniak** [comment]
Hi, I've managed to create a minimal reproduction:

https://github.com/krzysztofpniak/twMergeStorybook

all you need to do is to install deps and run:
`yarn storybook` or `npm run storybook`

the line 2 of `stories/Button.jsx` is causing the build problem

**Comment by dcastil** [comment]
Thanks! Will take a look.

**Comment by dcastil** [comment]
Just checked out your repo and it seems that the issue is that Storybook is using webpack v4 by default which is quite old and doesn't understand ESM or modern JS syntax like optional chaining.

I tried using [webpack5](https://storybook.js.org/docs/react/builders/webpack#webpack-5) and then it compiled fine. So if you can upgrade to webpack 5 in Storybook, this is the best option.

Related:
- https://github.com/storybookjs/storybook/issues/17200
- https://github.com/storybookjs/storybook/issues/16690

**Comment by krzysztofpniak** [comment]
Thanks a lot for your time and hits. You were right, with webpack 5 it works like a charm!
