### ISSUE TITLE
tailwindcss-intellisense throws cssConflict for irrelevant classNames

### ISSUE THREAD

**Issue by ThaJay** [dcastil/tailwind-merge#208]
Firstly thank you for this module, it's quite needed for a decent size codebase with TailwindCss

As shown in the screenshot example, tailwindcss-intellisense warns me about a cssConflict while the offending element className has no relation with the one used with `twMerge`.
![image](https://user-images.githubusercontent.com/9341747/226573521-38f289d8-350e-4220-ba76-e2389dc0dcb8.png)
![image](https://user-images.githubusercontent.com/9341747/226573665-26b858f6-d5a1-4746-a454-487668b4602a.png)

**Comment by dcastil** [comment]
Hey @ThaJay! 👋 

I think this is an issue with the Tailwind CSS Intellisense VS Code extension. tailwind-merge can't highlight anything in VS Code since it doesn't have a VS Code extension.

It's probably better if you open an issue in the repository of the VS Code extension: https://github.com/tailwindlabs/tailwindcss-intellisense

**Comment by dcastil** [comment]
No worries. 😊
