### ISSUE TITLE
Doesn't merge arbitrary values with custom calc

### ISSUE THREAD

**Issue by opswiz** [dcastil/tailwind-merge#255]
### Describe the bug

Doesn't merge arbitrary values with calc. I hope this is a valid expectation?

### To Reproduce

Run the following 

```js
twMerge('mt-[calc(theme(fontSize.4xl)/1.125)] mt-2')
```

returns `mt-[calc(theme(fontSize.4xl)/1.125)] mt-2`

### Expected behavior

Expected to return just `mt-2`

### Environment

-   tailwind-merge version: 1.13.2

**Comment by dcastil** [comment]
Hey @opswiz! 👋

Ah yeah, I'll fix that.

tailwind-merge searches for a number with a length unit between the brackets to mark it as a length value (which in this case it won't find), otherwise it thinks it's a color. In the meantime you can use the class `mt-[length:calc(theme(fontSize.4xl)/1.125)]` to make merging work correctly.

Thanks for reporting!

**Comment by dcastil** [comment]
Note to myself:

There are several things I can improve here (I'll do all of them).

### Improve signal that arbitrary value is a length

tailwind-merge should take `calc(` as a signal that the value is a length. But I should also take other CSS functions into account that can be used as lengths (https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#math_functions) that can be used on the top level of a property.
- `calc`
- `min`
- `max`
- `clamp`

### Explain in docs how to get merging to work correctly in ambiguous cases

There are cases where tailwind-merge can't know what value a class has since tailwind-merge only looks at the class syntax and doesn't have access to the Tailwind CSS config, e.g. `text-[theme(someScale.someValue)]`. I should add the info to the docs that one can use the Tailwind-supported data-type labels to resolve that, e.g. with `text-[length:theme(someScale.someValue)]`.

- https://tailwindcss.com/docs/adding-custom-styles#resolving-ambiguities
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types

### Don't check for length in arbitrary values of margin and padding classes

The class `mt-[theme(someScale.someValue)]` isn't ambiguous because Tailwind CSS only allows length values there. So there is no point in even checking what type the arbitrary property is. I could allow any arbitrary properties in the margin and padding themes scales to fix this for at least those classes.
