### ISSUE TITLE
twMerge not merging flex classes

### ISSUE THREAD

**Issue by jacknevitt** [dcastil/tailwind-merge#310]
### Describe the bug

Flex classes are not being merged correctly.

### To Reproduce

```ts
twMerge("flex-grow", "flex-grow-0");
```

### Expected behavior

```ts
twMerge("flex-grow", "flex-grow-0");
// expected: "flex-grow-0"
// actual: "flex-grow flex-grow-0"

twMerge("flex-shrink", "flex-shrink-0");
// expected: "flex-shrink-0"
// actual: "flex-shrink flex-shrink-0"

twMerge("basis-0", "basis-auto");
// expected: "basis-auto"
// actual: "basis-0 basis-auto"
```

### Environment

-   tailwind-merge version: 1.12.0

**Comment by dcastil** [comment]
Hey @jacknevitt! 👋

The `flex-grow` and `flex-shrink` classes don't exist in Tailwind, I think you meant `grow` and `shrink` which should be merged correctly.

The `basis-auto` class was indeed not merged correctly in v1.12.0 and was fixed in https://github.com/dcastil/tailwind-merge/pull/242 which landed in v1.13.1.

So switching from `flex-grow/shrink-*` to just `grow/shrink-*` and upgrading to v1.13.1 or later should fix all these issues.

PS: Thanks for your patience, I'm just coming back from a vacation.

**Comment by jacknevitt** [comment]
Thanks for your response. I have been using `flex-grow`, `flex-shrink` etc. because they appear in my intellisense suggestions and they add the correct styles to my elements. If they are just aliases for `grow` and `shrink`, I will use these instead.

**Comment by dcastil** [comment]
Ahh interesting! I also see that they're in the Tailwind codebase and marked as deprecated. So probably better to switch to `grow` and `shrink`.

https://github.com/tailwindlabs/tailwindcss/blob/5366d242c25aa5e008c38a53cdfeca1cf0a22e44/src/corePlugins.js#L786

**Comment by dcastil** [comment]
I assume that your issue is resolved, so I'm closing this issue. Let me know if I should reopen it again.
