### ISSUE TITLE
flex-shrink and flex-shrink-0 should override each other

### ISSUE THREAD

**Issue by erdemdev** [dcastil/tailwind-merge#340]
`flex-shrink` class should override any existing `flex-shrink-0` class and vice versa. The same applies to `flex-grow` and `flex-grow-0`.

![code](https://github.com/dcastil/tailwind-merge/assets/38112087/5610a8ed-c4f4-4726-b315-ba0fe0a58f25)

![1699290334](https://github.com/dcastil/tailwind-merge/assets/38112087/3abf8c73-bbf6-437d-b62e-24a796fcfb8c)

tailwind-merge version: 2.0.0

**Comment by dcastil** [comment]
Hey @erdemdev! 👋

That's because tailwind-merge only detects the [official classes](https://tailwindcss.com/docs/flex-shrink) `shrink` and `shrink-0`. The `flex-` prefix is still supported in Tailwind CSS but deprecated and will probably be removed in the future.

You can read more details about this in https://github.com/dcastil/tailwind-merge/issues/310.

**Comment by erdemdev** [comment]
Thank you for the quick response. I totally forgot to check closed issues. Sorry about that.

**Comment by dcastil** [comment]
No worries, I'm happy to help!
