### ISSUE TITLE
Incorrect typing on classGroups extend on v2

### ISSUE THREAD

**Issue by castrolem** [dcastil/tailwind-merge#343]
### Describe the bug

Upgrading from v1 where I used the extension scheme to add the `text-balance` property to tailwind merge, I changed the format from

```
// example class group config on v1
const customTwMerge = extendTailwindMerge({
  classGroups: {
    textBalance: ["text-balance"],
  },
});
```

to the following code

```
// example class group config on v2
const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "text-balance": ["text-balance"],
    },
  },
});
```

### Expected behavior

TS typings should not restrict custom properties

### Environment

-   tailwind-merge version: 2.0.0

### Additional context

By adding a `@ts-ignore` the error can be ignored and the properties are rendered correctly, so it is just the TS typing what's failing.

**Comment by dcastil** [comment]
Hey @castrolem!

If you're adding custom properties, you also need to add them as a TypeScript generic argument to the function. This is in place so that you don't accidentally use keys that don't exist in the config.

This should make it work:

```ts
const customTwMerge = extendTailwindMerge<'text-balance'>({
  extend: {
    classGroups: {
      "text-balance": ["text-balance"],
    },
  },
});
```

If you're interested, here is more info on the TypeScript types of `extendTailwindMerge`: https://github.com/dcastil/tailwind-merge/blob/v2.0.0/docs/configuration.md#typescript-types-for-extendtailwindmerge

**Comment by castrolem** [comment]
Oh wow. I totally missed that from the docs and I went through them before 😨. Thank you. This totally solves my inquiry.

**Comment by dcastil** [comment]
Nice! Then I'm closing this issue as resolved. Let me know in case you still need help with this.
