### ISSUE TITLE
Add support for Tailwind 3.4's `size-*`

### ISSUE THREAD

**Issue by ahkhanjani** [dcastil/tailwind-merge#359]
`size-*` should override both `h-*` and `w-*` classes.

**Comment by dcastil** [comment]
I'll add support for all Tailwind CSS v3.4 features in the coming days.

**Comment by imekachi** [comment]
@dcastil Could you take a look at this test case?

```ts
expect(twMerge('w-5 size-10 w-12 h-3')).toBe('w-12 h-3')
```

<img width="1512" alt="image" src="https://github.com/dcastil/tailwind-merge/assets/148201348/8cf7bd2d-d627-4dbb-a1d1-b60aa1dc4a1e">

Since `w` and `h` override every property that `size` provides, should `size` be removed?
For some reason, it's not.

**Comment by dcastil** [comment]
Hey @imekachi! 👋

This is intentional and shouldn't cause any issues: `w-12` and `h-3` would get applied in CSS although the `size-10` class is present. I wrote an explanation to a similar question in https://github.com/dcastil/tailwind-merge/discussions/156#discussioncomment-3918447 which also applies here.

**Comment by imekachi** [comment]
> Hey @imekachi! 👋
> 
> This is intentional and shouldn't cause any issues: `w-12` and `h-3` would get applied in CSS although the `size-10` class is present. I wrote an explanation to a similar question in https://github.com/dcastil/tailwind-merge/discussions/156#discussioncomment-3918447 which also applies here.

I see. It makes sense now. Thanks for the explanation.
