### ISSUE TITLE
bg-gradient not overriding bg

### ISSUE THREAD

**Issue by dinyo** [dcastil/tailwind-merge#376]
### Describe the bug

i dont know if intended that way, but bg-gradient not removing bg-[color] before it.

### To Reproduce

```
import { twMerge } from 'tailwind-merge'
console.log(twMerge('px-1 bg-blue-500 bg-white px-5 bg-gradient-to-b from-red-500 to-red-200'));
```

output:
`"bg-white px-5 bg-gradient-to-b from-red-500 to-red-200"`

### Expected behavior

output:
`"px-5 bg-gradient-to-b from-red-500 to-red-200"`

### Environment

-   tailwind-merge version: 2.2.1

**Comment by dcastil** [comment]
Hey @dinyo! 👋

tailwind-merge doesn't override `bg-<color>` classes when using `bg-gradient-to-*` in its default config because they target different CSS properties and could be used in together.

E.g. you could use a background-image with transparency and then apply a background-color which will be applied for all transparent pixels of the background-image.

But if you want both to remove each other, you can configure your tailwind-merge instance to do it:

```ts
const twMerge = extendTailwindMerge({
    extend: {
        conflictingClassGroups: {
            'bg-image': ['bg-color'],
            'bg-color': ['bg-image']
        }
    }
})
```

**Comment by dinyo** [comment]
thanks @dcastil, i understand now 👍.
