### ISSUE TITLE
Tailwind merge doesn't apply custom class passed via props when there's screen size variant

### ISSUE THREAD

**Issue by juniorforlife** [dcastil/tailwind-merge#380]
### Describe the bug
I have a `cn` util which I copied from shadcn:
```
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
```
Then I use it in my Button.svelte as follow:
```
<script lang="ts">
  import { cn } from '$lib/utils';

  export let variant: 'primary' | 'secondary' | 'outline' | 'destructive' = 'primary';
  export let size: 'base' | 'lg' = 'base';
  export let loading: boolean = false;
  export let disabled: boolean = false;
</script>

<button
  {...$$restProps}
  class={cn(
    'relative cursor-pointer rounded-full text-center font-medium text-white',
    {
      'bg-purple hover:bg-purple/80': variant === 'primary',
      'bg-white/10': variant === 'secondary',
      'border-[1.5px] border-white/40 bg-transparent': variant === 'outline',
      'bg-red-600 hover:bg-red-500': variant === 'destructive',
      'cursor-not-allowed opacity-50': disabled,
      'h-8 sm:h-9': size === 'base',
      'h-11 min-w-[9rem] sm:min-w-[11rem] sm:text-lg': size === 'lg',
    },
    $$restProps.class
  )}
  on:click
  {disabled}
>
  <div class={`${loading ? 'invisible' : 'visible'} flex items-center justify-center `}>
    <slot />
  </div>
</button>
```

When I pass a custom class like this `<Button class="w-full h-14">Create</Button>`, the `h-14` class isn't applied.
What I notice is when I remove `sm:h-9` then the code works as expected. 

### To Reproduce

I provided the code above. 

### Expected behavior

`h-14` should override `h-8 sm:h-9`

### Environment

-   tailwind-merge version:  ^2.2.1

**Comment by dcastil** [comment]
Hey @juniorforlife! 👋

tailwind-merge only overrides direct conflicts like the one between `h-8` and `h-14` but treats classes with modifiers like `sm:` as a separate type of class. So you'd need to write `<Button class="w-full h-14 sm:h-14">Create</Button>` to override both classes.

I acknowledge that this might be unexpected in some cases like yours, but there are a few reasons why tailwind-merge behaves this way:
- User expectations: Many users expect that the class with the modifier would stay there when changing the base class. Otherwise you'd always need to redefine all the classes with modifiers again when you only want to change the base class. If I'd flip the behavior, other users would see the new behavior as a bug as well.
- Other modifiers: tailwind-merge doesn't have any info internally about what all the modifiers mean and just resolves conflicts among classes with the same modifier. There are a lot of modifiers in Tailwind CSS and then the question appears what to do in other cases like `hover:`, `group-hover:`, `disabled:`, etc. It would definitely be unexpected to remove all classes with the other modifiers. The alternative is that tailwind-merge would need to have different behavior based on the modifier which would increase the already very large config and also lead to confusion since tailwind-merge does different things depending on the modifier.

I also don't like how it's necessary to supply all the screen sizes, though. Maybe it would indeed be better to wipe out all the screen size modifiers when adding a base class. But I'm not sure about it, e.g. I'd also need to think about what happens when you have a case like this:

```ts
twMerge('h-1 sm:h-2 md:h-3', 'sm:h-4')
```

Should the `sm:h-4` remove all preceding height classes, or only the `sm:` and `md:` variants? 🤔

Definitely no straight forward solution here.

**Comment by juniorforlife** [comment]
@dcastil Thank you for your thorough reply. I believe this issue is a small nuisance and not likely to occur too frequently. Nonetheless, I believe it should be noted for clarity to prevent any misunderstandings among future users.
