### ISSUE TITLE
Tailwind merge wrongly merge background-opacity with background-color.

### ISSUE THREAD

**Issue by ngtrthinh169TPC** [dcastil/tailwind-merge#448]
### Describe the bug

When `background-color` is used with `background-opacity`, the latter written will be removed by tailwind-merge. This disallows any efforts to make transparent effects.

### To Reproduce

https://codesandbox.io/p/sandbox/unruffled-bose-cssr35?file=%2Fsrc%2Findex.ts%3A21%2C71
![image](https://github.com/user-attachments/assets/d27ad08b-e68d-4a30-859c-93f14bd7e7d5)

### Expected behavior

`background-color` and `background-opacity` should not collide. Both of the classes should be kept.

### Environment

-   tailwind-merge version: 2.4.0

**Comment by dcastil** [comment]
Hey @ngtrthinh169TPC! 👋

This is indeed a bug. The problem is that tailwind-merge only accepts numbers within arbitrary values of opacities and then erroneously defaults to classify it as a background-color class. I'll fix it in the coming days.

In the meantime you can work around it by using `bg-opacity-[0.48]` instead. That should work without issues.
