### ISSUE TITLE
there is no theme options for extendTailwindMerge

### ISSUE THREAD

**Issue by rhostem** [dcastil/tailwind-merge#61]
Hi. thanks for nice library.

in main branch, `extendTailwindMerge` has option for theme.

```js
const customTwMerge = extendTailwindMerge({
    // ↓ Add values to existing theme scale or create a new one
    theme: {
        spacing: ['sm', 'md', 'lg'],
    },
    // ↓ Add values to existing class groups or define new ones
    classGroups: {
        foo: ['foo', 'foo-2', { 'bar-baz': ['', '1', '2'] }],
        bar: [{ qux: ['auto', (value) => Number(value) >= 1000] }],
    },
    // ↓ Here you can define additional conflicts across class groups
    conflictingClassGroups: {
        foo: ['bar'],
    },
})
```

But in [v0.8.2](https://github.com/dcastil/tailwind-merge/tree/v0.8.2), theme options is missing.
v0.8.2 is deployed in npm registry so I cannot use it. I have additional spacing options in my tailwind theme. But to merge with it, I had to create custom merge func like this.

```
const customTwMerge = extendTailwindMerge({
  classGroups: {
    pt: [(v: string) => /[\d|xs|sm|md|lg|xl]/.test(v)],
  },
});
```

is theme options is going to be removed from `Config`? or is there something wrong with npm registry?

**Comment by dcastil** [comment]
Hey @rhostem! The theme is not working in v0.8.2 because that feature was added afterwards and I didn't release a new version with that change. But I [released v0.9.0](https://github.com/dcastil/tailwind-merge/releases/tag/v0.9.0) now where that should work as expected.

I'm closing this issue here, let me know if this didn't solve your issue and I'll reopen it again.
